apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-rails-tls
  namespace: default
spec:
  secretName: k8s-rails-tls
  issuerRef:
    name: letsencrypt-prod
  dnsNames:
  - $DNS_WEBSITE
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
